### ISSUE TITLE
text-transform wrongly reported as being related to CSS3 Transforms

### ISSUE THREAD

**Issue by miclf** [anandthakker/doiuse.com#24]
![doiuse](https://cloud.githubusercontent.com/assets/3188746/6392960/38a32af8-bdc6-11e4-9070-f8e77dd0f2be.png)

The title says everything :-)
You can find an example [here](http://doiuse.com/?url=http%3A%2F%2Fzeldman.com&browsers=&css=).

**Comment by anandthakker** [comment]
@miclf Ahh... that's slightly embarrassing :).  Thanks for the report!
