### ISSUE TITLE
SyntaxError: JSON.parse: unexpected end of data

### ISSUE THREAD

**Issue by SebastianZ** [anandthakker/doiuse.com#25]
I tried to test http://qsurvey.mozilla.com/reportsview/?key=28049-4099407-a5dd5e6bb02a03f6c2dec0183a31e37e on doiuse.com and it failed with the following error message:

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 143 of the JSON data

fetch/<@http://doiuse.com/bundle.js:104:16
once/<@http://doiuse.com/bundle.js:2371:12
loadFunc@http://doiuse.com/bundle.js:2251:9
readystatechange@http://doiuse.com/bundle.js:2187:13
```

Sebastian

**Comment by anandthakker** [comment]
Thanks for the report @SebastianZ ... traveling now, but will check it out asap!

**Comment by AmaZili** [comment]
Same error on parsing with http://amazili-communication.com

There was an error -- shocking, I know. If you've got a minute, please report it!

SyntaxError: JSON.parse: unexpected end of data at line 1 column 85 of the JSON data

fetch/<@http://doiuse.com/bundle.js:104:16
once/<@http://doiuse.com/bundle.js:2371:12
loadFunc@http://doiuse.com/bundle.js:2251:9
readystatechange@http://doiuse.com/bundle.js:2187:13

**Comment by anandthakker** [comment]
This should be fixed!

**Comment by SebastianZ** [comment]
Yes, there is no parsing error anymore. Thanks for fixing this!

The pages just output a CssSyntaxError errors now.
For http://amazili-communication.com it looks like a bug within the page, though for the Mozilla page it looks like a HTML is parsed as CSS. Should a separate bug be filed for that?

Sebastian

**Comment by anandthakker** [comment]
Ah thanks - I had started but not submitted the new issue, which is here: #28

**Comment by AmaZili** [comment]
Seems to be fixed for https://amazili-communication.com.com as well.
Sorry but I can't say if we fixed something in the page since march..., we have done a lot on this page backend.

Thanks.
