### ISSUE TITLE
is hanging with postcss

### ISSUE THREAD

**Issue by bcardarella** [anandthakker/doiuse.com#26]
I have a moderate sized css file (less than 5,000 lines) that I am running through several postcss filter:
- postcss-import
- postcss-simple-var
- postcss-nested
- autoprefixer
- doiuse

All the other filters ran just fine, when I added doiuse to the end the compilation hangs. I'm not sure how to diagnose this. Any direction you can give?

**Comment by anandthakker** [comment]
@bcardarella Thanks for the report.  Can you let me know your version of postcss?

**Comment by bcardarella** [comment]
4.1.6

**Comment by anandthakker** [comment]
@bcardarella Okay, thanks.  I'll check it out and keep you posted!

**Comment by anandthakker** [comment]
@bcardarella Just updated and it seems to be working on my side.  Can you give it a try with v0.3.3?
