### ISSUE TITLE
Failure when using negative queries

### ISSUE THREAD

**Issue by openjck** [anandthakker/doiuse.com#30]
**Steps to reproduce:**

1. Provide an inverse browser-targeting query (for example, *not ie <= 8*)
2. Provide some CSS
3. Start the test

**Result:**

Test results are not printed. An error is shown and the doiuse.com application crashes.

**Comment by anandthakker** [comment]
Thanks for the report!  Fixed online (http://www.doiuse.com/?url=&browsers=%3E%201%25%2C%20not%20ie%20%3C%3D%208&css=.something%3Aafter%20%7B%20display%3A%20flex%3B%20%7D), via `doiuse@2.2.1`
